##################################
# 该配置文件可以放置在以下三个目录里面
# /etc/gin-api-demo
# $HOME/.gin-api-demo
# App.RootDir/config
##################################
# 服务配置
server:
  appName: gin-api-demo
  env: dev
  runMode: debug
  port: :8090
  jwtSecret: sdjf934785974FJMSMBN043534utjldsdfLKJ}P|Q@#!glkdjg

context:
  timeout: 5s

token:
  timeout: 3600s

# 数据库配置
database:
  driver: mysql
  addr: 127.0.0.1:3306
  user: apiuser
  password: 123456
  dbname: gin_api_demo
  tablePrefix: tb_
  debug: true
  maxOpenConns: 1000
  maxIdleConns: 0

# redis缓存配置
redis:
  host: 127.0.0.1
  port: :6379
  db: 1
  protocol: tcp
  maxIdle: 3
  maxActive: 3
  idleTimeout: 60s

# log配置
log:
  level: DEBUG
  path: /var/log/go/
  fileName: system.log

# cors 跨域资源共享
cors:
  allowAllOrigins: true
  allowMethods:
    - GET
    - HEAD
    - POST
    - PUT
    - DELETE
    - CONNECT
    - OPTIONS
    - TRACE
    - PATCH
  allowHeaders:
    - Origin
    - Accept
    - Content-Type
    - Authorization
  exposeHeaders:
    - Cache-Control
    - Content-Language
    - Content-Type
    - Expires
    - Last-Modified
    - Pragma
  allowCredentials: false
  maxAge: 2m

# mail 邮件配置
mail:
  sendOpen: false
  from: test123@qq.com
  to:
    - test123@qq.com
    - test456@qq.com
  host: 127.0.0.1
  port: 456
  user: test123
  password: test123

